### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by themightyoarfish** [martinbenson/deep-photo-styletransfer#11]
What would be good in my opinion is to make the scripts operate on single files (or 4 files, that is) and not directories. I think it's very inconvenient if you want to process images one by one and I don't know why the upstream author chose to do it this way.

**Comment by martinbenson** [comment]
I think you're right. Better to do any iteration a level up.

IF ANYONE HATES THE IDEA SHOUT UP NOW, otherwise will look to move to interface as above.

**Comment by martinbenson** [comment]
Done.
