### ISSUE TITLE
Non docker version missing gen_laplacian/ directory and

### ISSUE THREAD

**Issue by ProGamerGov** [martinbenson/deep-photo-styletransfer#12]
For those already running [Neural-Style](https://github.com/jcjohnson/neural-style), and/or similar projects, many of the dependencies are already setup.

 When running `git clone`, the `gen_laplacian/` and everything it contains, is missing.

**Comment by martinbenson** [comment]
Not sure what you're driving at with this?  The gen_laplacian isn't needed now in my version...

**Comment by ProGamerGov** [comment]
@martinbenson I assumed it was still needed because of the `-laplacian` parameter in `deepmatting_seg.lua`, though looking at the code, is `gen_all.py` now the way for creating the `-laplacian` file?

**Comment by martinbenson** [comment]
Oh, i see. Yeah, the laplacian files get generated if needed be in gen_all.py (if they've already been done it just reads them from disk). it's all much faster and less messing about now.

**Comment by ProGamerGov** [comment]
@martinbenson When using `gen_all.py`, how does one manipulate the individual `deepmatting_seg.lua` and `neuralstyle_seg.lua` parameters?

**Comment by martinbenson** [comment]
I pulled many through to arguments on gen_all.py. See project readme for which. If there are more that would be useful then let me know or just make an edit and do a pull request.

**Comment by ProGamerGov** [comment]
@martinbenson I would prefer a way to have different parameters for each Lua script, but the ADAM optimizer definitely needs the corresponding `-learning_rate` parameter.

For other parameters, `-cudnn_autotune` should be toggle-able due to the nature of the command. The `-content_layers` and `-style_layers` parameters should be controllable so the user can control the target "levels" at which changes take place in the image. The various weights should be controllable as well for each script. `-lbfgs_num_correction` helps deal with larger image sizes using the `lbfgs` optimizer as per [this post](https://github.com/jcjohnson/neural-style/issues/351#issuecomment-265693607). 

Seeing how others have manipulated the `-lambda`, `-patch`, `eps`, `-f_radius`, and `-f_edge` parameters, these might be useful for controlling the level of photo realism produced by the final Lua script.

**Comment by ProGamerGov** [comment]
@martinbenson After playing around with `gen_all.py`, I can see now why you went with this as opposed to manually running the scripts. It's a lot more efficient than the original project. Great work!

Though it seems that the traditional quirks of Neural-Style still apply, where the most changes to your content image occur depending on how close your image size is to the size of the training images used to train the model. I am curious to see if my optimization tricks will help speed things up, but the Multires technique might need to be implemented as an option to provide more control over the effects caused by the image size parameter.
