### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by ProGamerGov** [martinbenson/deep-photo-styletransfer#14]
Trying to run the code seems to result in this error: 

```
ubuntu@ip-Address:~/deep-photo-styletransfer$ python3 gen_all.py -gpus 0 -in_dir in/ -style_dir style/ -in_seg_dir in_seg/ -style_seg_dir style_seg/ -tmp_results_dir tmp_results/ -results_dir results/ -lap_dir lap/ -width 1000 -opt lbfgs -stage_1_iter 1000 -stage_2_iter 1000
Traceback (most recent call last):
  File "gen_all.py", line 233, in <module>
    width, gpus, s1_iter, s2_iter, args.optimiser)
  File "gen_all.py", line 17, in deep_photo
    n = int(math.ceil(float(num_imgs) / num_gpus))
ZeroDivisionError: float division by zero
ubuntu@ip-Address:~/deep-photo-styletransfer$
```

**Comment by martinbenson** [comment]
-gpus is number of GPUs! Must be at least one! Doesn't work on CPU.

**Comment by ProGamerGov** [comment]
@martinbenson Ah, ok. I thought it was similar to the `-gpu` parameter used by Neural-Style. 

Though there is a new issue: 

```
ubuntu@ip-Address:~/deep-photo-styletransfer$ python3 gen_all.py -gpus 1 -in_dir in/ -style_dir style/ -in_seg_dir in_seg/ -style_seg_dir style_seg/ -tmp_results_dir tmp_results/ -results_dir results/ -lap_dir lap/ -width 1000 -opt lbfgs -stage_1_iter 1000 -stage_2_iter 1000

ubuntu@ip-Address:~/deep-photo-styletransfer$

Nothing seems to happen. I placed both mask images in their separate directories, and both the content and style image in their directories. 

```

**Comment by martinbenson** [comment]
Perhaps try absolute paths rather than relative ones. Note that if you've used docker then you'll probably need to map a directory from the host to the container and use the absolute path to that.

Also, note that the files in each directory all need to have the same names. In the original repo there was e.g. in1.png and tar1.png, but now everything should be in1.png across all directories (though you can now name the files whatever you want - provided the names are consistent across all 4 directories).

**Comment by ProGamerGov** [comment]
So it seems the file in my directories got delete somehow, so I had to replace the images.

```
ubuntu@ip-Addres:~/deep-photo-styletransfer$ python3 gen_all.py -gpus 1 -in_dir in/ -style_dir style/ -in_seg_dir in_seg/ -style_seg_dir style_seg/ -tmp_results_dir tmp_results/ -results_dir results/ -lap_dir lap/ -width 1000 -opt lbfgs -stage_1_iter 1000 -stage_2_iter 1000
Skipped tropical_island_girl.png due to missing files.

ubuntu@ip-Address:~/deep-photo-styletransfer$
```

I assume the above error is related to the incorrect naming pattern.

**Comment by martinbenson** [comment]
Yeah, it goes through in_dir and checks for every file in there that there's a file with the same name in the other 3 directories. If not, it skips it and gives that message (which could probably be clearer in fairness).

**Comment by ProGamerGov** [comment]
@martinbenson Thanks for the help, it's working now!
