### ISSUE TITLE
Continuing from where you left off while running the gen_all.py script

### ISSUE THREAD

**Issue by ProGamerGov** [martinbenson/deep-photo-styletransfer#15]
Currently, if the `gen_all.py` script is stopped for any reason between the `neuralstyle_seg.lua` and `deepmatting_seg.lua` steps, one will need to re-run the `neuralstyle_seg.lua` step again, which can become very time consuming. 

Would it be possible to add a way to start the `gen_all.py` script past the `neuralstyle_seg.lua` step?

**Comment by martinbenson** [comment]
As a hack, you could just set stage 1 iterations to 1. Longer term, I wonder if there's any real need to have the two steps. neuralstyle_seg.lua acts as initialisation for deepmatting_seg.lua from what I can tell. Not obvious that doing say 2000 iterations of just deepmatting_seg.lua would be much different to doing 1000 and 1000.

**Comment by ProGamerGov** [comment]
@martinbenson 

> Not obvious that doing say 2000 iterations of just deepmatting_seg.lua would be much different to doing 1000 and 1000.

The only different between the two appears the be the inclusion of the laplacian, which can be modified to be an optional parameter. 

> Longer term, I wonder if there's any real need to have the two steps. 

According to the original project creator, they can be merged together: https://github.com/luanfujun/deep-photo-styletransfer/issues/13#issuecomment-289850854


I have myself been working on integrating these features into the current version of Neural-Style, as I did with the code from Gatys' most recent research paper. I have created this modified version of Neural-Style here: https://gist.github.com/ProGamerGov/d3988b914c92220ae45aa5bb1e31d6a7, that seems to perform the `deepmatting_seg.lua` step correctly if given an input laplacian. Though it does not currently support the masks for either or the content or the style images, as I don't know how to make the masks work correctly (Maybe you know how to do this?). The code is based on a version of Neural-Style from [before December 2016](https://github.com/jcjohnson/neural-style/blob/197ad4218f0536b3b284ea322a190d507f4d8757/neural_style.lua), and thus in order to add features into the latest version of Neural-Style, you may have to first convert some of the code in the new format. Note that some of the parameters were removed and hard-coded to specific options/values in both `deepmatting_seg.lua`, and `neuralstyle_seg.lua`, so you will need to select the correct options to match the results from deep-photo-styletransfer without masks. The current version of Neural-Style is more efficiently setup.

**Comment by ProGamerGov** [comment]
Comparing my modified neural_style.lua's results to the main project's results: 

**The Original Project's Content, Style, and the Mask Images:** 

<p align='center'>
  <img src='https://raw.githubusercontent.com/luanfujun/deep-photo-styletransfer/master/examples/input/in9.png' height='194' width='290'/>
  <img src='https://raw.githubusercontent.com/luanfujun/deep-photo-styletransfer/master/examples/style/tar9.png' height='194' width='290'/>
</p>

<p align='center'>
  <img src='https://raw.githubusercontent.com/luanfujun/deep-photo-styletransfer/master/examples/segmentation/tar9.png' height='194' width='290'/>
  <img src='https://raw.githubusercontent.com/luanfujun/deep-photo-styletransfer/master/examples/segmentation/tar9.png' height='194' width='290'/>
</p>

**Resulted in:** 

![](https://raw.githubusercontent.com/luanfujun/deep-photo-styletransfer/master/examples/final_results/best9_t_1000.png)

---

**My modified [`neural_style_laplacian.lua`](https://gist.github.com/ProGamerGov/d3988b914c92220ae45aa5bb1e31d6a7) (`gen_all.py` was only used to make the laplacian) resulted in:** 

![](https://i.imgur.com/bNwYsMl.png)

**Then Repeating The Process With Histogram Matching:**

![](https://i.imgur.com/ljwopIK.png)

**The final histogram matching output with Luminance-Only transfer:** 

<p align='center'>
  <img src='https://i.imgur.com/sMF2HY5.png' height='194' width='290'/>
  <img src='https://i.imgur.com/ZxsjGgR.png' height='194' width='290'/>
</p>

**Comment by ProGamerGov** [comment]
Histogram Matching (From style to content) only on the first step, seems to make the difference: 

![](https://i.imgur.com/TzQfoEM.png)

Lumiance-Only on the final output (Not full Luminance Transfer, only from the last Luminance-Only Transfer step was used, from the content image to the final output): 

![](https://i.imgur.com/Y8aRgaK.png)

**Comment by Multiboxer** [comment]
When I had this issue I modified the file so part 1 read `part1_cmd = ' '` then saved it as gen_dm.py

**Comment by martinbenson** [comment]
This is now possible via the -init_image parameter.
