### ISSUE TITLE
Permission denied error when running without docker

### ISSUE THREAD

**Issue by themightyoarfish** [martinbenson/deep-photo-styletransfer#19]
I have everything installed an no clue about docker, so I'm going without. But the `gen_all.py` script attempts to access `/root/deep_photo/neuralstyle_seg.lua` which obv doesn't exist per se. I assume this comes from the assumption of being run inside a container (?)

Could this be fixed to make it work in both cases?

**Comment by martinbenson** [comment]
Yeah, it would be best not to have absolute paths and then it would work both ways, I can't remember why I made the paths absolute now, but I'll try putting them back to relative paths.

**Comment by martinbenson** [comment]
Relative paths work fine, so have committed a change to move to that.
