### ISSUE TITLE
luajit: invalid arguments: table number expected arguments: [*DoubleTensor*] DoubleTensor double

### ISSUE THREAD

**Issue by subzerofun** [martinbenson/deep-photo-styletransfer#25]
Just updated my local install and tried to run 
`deep_photo.py -content_image examples/input/in1.png -style_image examples/style/in1.png -output_image examples/test/test1.png -image_size 200`

and got this error:

```
(...)
Iteration 100 / 2000
  Content 1 loss: 676900.937500
  Style 1 loss: 9288.229370
  Style 2 loss: 41201.791992
  Style 3 loss: 17633.553467
  Style 4 loss: 590856.640625
  Style 5 loss: 927.143478
  Total loss: 1336808.296432
/Users/ME/torch/install/bin/luajit: invalid arguments: table number
expected arguments: [*DoubleTensor*] DoubleTensor double
stack traceback:
	[C]: at 0x099eb700
	[C]: in function 'div'
	deepmatting_seg.lua:387: in function 'SmoothLocalAffine'
	deepmatting_seg.lua:303: in function 'maybe_save'
	deepmatting_seg.lua:351: in function 'opfunc'
	/Users/ME/torch/install/share/lua/5.1/optim/lbfgs.lua:211: in function 'lbfgs'
	deepmatting_seg.lua:361: in function 'main'
	deepmatting_seg.lua:696: in main chunk
	[C]: in function 'dofile'
	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x0109786360
```

Do you have an idea what could cause this error?

**Comment by martinbenson** [comment]
Sorry, I rushed out the commit with a few mistakes in it. I spotted them and fixed, but i think you must have pulled in the interim. If you pull again the error should go away.

**Comment by pedropgusmao** [comment]
Hi, I just  checked out the repository and I am getting the same error. Could this be something else.

**Comment by subzerofun** [comment]
@martinbenson 
Could you please reopen the issue? I have pulled the last updates and unfortunately i still get this error.

**Comment by pedropgusmao** [comment]
I guess what is happening is that SmoothLocalAffine is not receiving a tensor in the "output" variable.

**Comment by martinbenson** [comment]
Sorry guys, my bad, I was being monumentally dumb! Anyhow, I think that it really is fixed now!

**Comment by subzerofun** [comment]
Ok thanks, it looks like it's working again! I'm past the crashing 100 – 150 iterations from the previous runs.

But this version is now only working without the segmentation, isn't it?
https://github.com/martinbenson/deep-photo-styletransfer/issues/26

If i revert back to `git checkout 262a825` will that revision include the code that causes the `[*DoubleTensor*]` error?

Have you removed the segmentation code just for now (while you are working on a different implementation?) or is it simply because the conversion is faster without it?

**Comment by martinbenson** [comment]
@subzerofun That commit will be fine - I introduced the error above later than that.
