### ISSUE TITLE
Sample test

### ISSUE THREAD

**Issue by ThomasLengeling** [martinbenson/deep-photo-styletransfer#27]
Hi I am trying out the code, I successfully installed the docker and all its components, do you have sample code with image to try it out?
Thanks!

**Comment by ProGamerGov** [comment]
@ThomasLengeling You could try the example images from here: https://github.com/luanfujun/deep-photo-styletransfer/tree/master/examples

**Comment by martinbenson** [comment]
There are now examples and corresponding images in the readme.

**Comment by ProGamerGov** [comment]
@martinbenson You can use my example outputs here: https://i.imgur.com/nrh8Z1p.png as more examples if you want.
