### ISSUE TITLE
Example run command

### ISSUE THREAD

**Issue by DenisSergeevitch** [martinbenson/deep-photo-styletransfer#29]
Could you include an example run command to readme?

**Comment by artnose** [comment]
Indeed.  I can't reproduce the effects.  Getting bad results.

**Comment by DenisSergeevitch** [comment]
@artnose I trying to run it by:
`python3 deep_photo.py -image_size 1000 -init image -content_image /root/deep_photo/deepphoto/09.png -style_image /root/deep_photo/deepphoto/compare/09-style.png -output_image /root/deep_photo/deepresult/09.png -backend cudnn -cudnn_autotune
`
And also have a bad results

**Comment by subzerofun** [comment]
I didn't need the `-init` argument, maybe try running it without it. And don't try to use an `-image_size` of `1000` unless you have a GPU with 12 GB of VRAM. 

I've tried using an image size of `500` and `-cudnn_autotune` gave me wrong results. I then deleted the generated laplacian .csv file and tried it without the cudnn option and this time the output images looked alright!

Regarding image-size: Test a lower value like 400 and monitor your VRAM usage. If you still have memory left, increase the size by 100-200.

Try this cmd, it works for me:
`python3 deep_photo.py -content_image examples/input/in1.png -style_image examples/style/in1.png -output_image examples/test/test1.png -image_size 400`

This project is currently under development, so if you want to use segmentation masks you should try the original: https://github.com/luanfujun/deep-photo-styletransfer

---

Your results should look similar to this (GIF, to replay open in another tab):

![test_01-ps](https://cloud.githubusercontent.com/assets/17863119/25072915/e03d408e-22da-11e7-8df9-3c5b19cbe46d.gif)

**Comment by ProGamerGov** [comment]
@subzerofun He can also just use `git checkout 262a825` to get working masks.

**Comment by subzerofun** [comment]
@ProGamerGov Sorry, forgot about that!

**Comment by martinbenson** [comment]
I added some examples in the readme.
