### ISSUE TITLE
Unused color regions wasting GPU resources

### ISSUE THREAD

**Issue by ProGamerGov** [martinbenson/deep-photo-styletransfer#32]
I have long suspected that because the code uses all the color regions by default, GPU resources are wasted on dealing with the unused mask colors. I didn't realize the shear amount of wasted GPU memory until I conducted an experiment with two modified versions of the mask related code. By default, the code uses 9 different color regions regardless of how many color regions are actually in your mask images. 

---

![](https://i.imgur.com/xfXEkVe.png)

* The style mask I used contained 4 colors.

* The content mask I used contained 3 colors. 

* All three tests used the same input images. All the parameters used were the same as well.

* The control test uses the default [Neural-Style code](https://github.com/jcjohnson/neural-style).

* The graph covers the first 50-150 iterations from the very start of running the script.

* I used: `nvidia-smi -l 1 2>&1 | tee ~/neural-style/usage.log` to capture the data.

Oddly enough, with 4 style image mask colors, 3 content image mask colors, and only 4 color regions in the code, I can match the optimization levels of Neural-Style. 

Noting the issue I covered in the Wiki here: https://github.com/martinbenson/deep-photo-styletransfer/wiki/Mask-Creation-Errors, where unused content mask regions are still used, I think this may be related. I wonder why these empty regions are using so much GPU memory? 

I am also note sure why the usage graph stays constant for the normal Neural-Style code, but goes up and down for the code using the masks. Maybe this could indicate a potential other area for optimization?

---

For testing, this modified version of the code has only 4 usage colors: https://gist.github.com/ProGamerGov/ead2c1da7c0e68b401319d84dab15c57

And this version of the code has all 9 colors usable: https://gist.github.com/ProGamerGov/bcbd27a3d2e431adb73ef158d9990d93

In my modified versions of the code, the laplacian related code is removed, so anything laplacian related can be eliminated from my results.

**Comment by ProGamerGov** [comment]
**Experimenting with differing amounts of regions, with the same parameters as I described above:**

![](https://i.imgur.com/tTfMFZC.png)

![](https://i.imgur.com/4xfQNDb.png)

**Comment by ProGamerGov** [comment]
Looking at the code, there are two areas that could be modified to make the code more optimized.

The `color_codes` variable:

```
local color_codes = {'blue', 'green', 'black', 'white', 'red', 'yellow', 'grey', 'lightblue', 'purple'}
```

And the `ExtractMask` function:

```
function ExtractMask(seg, color, dtype)
  local mask = nil
  if color == 'green' then
  	mask = torch.lt(seg[1], 0.1)
  	mask:cmul(torch.gt(seg[2], 1-0.1))
  	mask:cmul(torch.lt(seg[3], 0.1))
  elseif color == 'black' then
  	mask = torch.lt(seg[1], 0.1)
  	mask:cmul(torch.lt(seg[2], 0.1))
  	mask:cmul(torch.lt(seg[3], 0.1))
  elseif color == 'white' then
  	mask = torch.gt(seg[1], 1-0.1)
  	mask:cmul(torch.gt(seg[2], 1-0.1))
  	mask:cmul(torch.gt(seg[3], 1-0.1))
  elseif color == 'red' then
    mask = torch.gt(seg[1], 1-0.1)
    mask:cmul(torch.lt(seg[2], 0.1))
    mask:cmul(torch.lt(seg[3], 0.1))
  elseif color == 'blue' then
    mask = torch.lt(seg[1], 0.1)
    mask:cmul(torch.lt(seg[2], 0.1))
    mask:cmul(torch.gt(seg[3], 1-0.1))
  elseif color == 'yellow' then
    mask = torch.gt(seg[1], 1-0.1)
    mask:cmul(torch.gt(seg[2], 1-0.1))
    mask:cmul(torch.lt(seg[3], 0.1))
  elseif color == 'grey' then
    mask = torch.cmul(torch.gt(seg[1], 0.5-0.1), torch.lt(seg[1], 0.5+0.1))
    mask:cmul(torch.cmul(torch.gt(seg[2], 0.5-0.1), torch.lt(seg[2], 0.5+0.1)))
    mask:cmul(torch.cmul(torch.gt(seg[3], 0.5-0.1), torch.lt(seg[3], 0.5+0.1)))
  elseif color == 'lightblue' then
    mask = torch.lt(seg[1], 0.1)
    mask:cmul(torch.gt(seg[2], 1-0.1))
    mask:cmul(torch.gt(seg[3], 1-0.1))
  elseif color == 'purple' then
    mask = torch.gt(seg[1], 1-0.1)
    mask:cmul(torch.lt(seg[2], 0.1))
    mask:cmul(torch.gt(seg[3], 1-0.1))
  else
  	print('ExtractMask(): color not recognized, color = ', color)
  end
  return mask:type(dtype)
end
```

**Comment by martinbenson** [comment]
The same thought occurred when I was going through the code, but it's difficult to be sure what the impact is just from that. So, thanks for testing! It'll be fairly easy to address though so let's get it sorted! (It'll be a week or so until I can get to it though unfortunately)

**Comment by martinbenson** [comment]
Ah, sorry,  just noticed that you said you've already made a quick fix - would you be happy to make a PR for it please?

**Comment by ProGamerGov** [comment]
@martinbenson I'll try to get a pull request up tomorrow. I think by default, the parameter should use all the regions (mimicking the old code), and then the user can specify their specific mask colours to optimize things if they want. This way new users are unlikely to run into errors, but are also easily able to make use of these changes.

**Comment by ProGamerGov** [comment]
@martinbenson The pull request is up, but I did not update the `deep_photo.py` Python script yet. 

I am not sure how to add the new paramter into the `deep_photo.py` Python script, and thus it may take a bit longer for people using the Python script, to get access to this new parameter. Maybe   @themightyoarfish knows how to add support for the new parameter?

**Comment by ProGamerGov** [comment]
It seems that the more color regions you use, the more resources are needed.

**Comment by ProGamerGov** [comment]
@martinbenson I think that we can actually farther optimize the resources used by masked regions in a way similar to VaKonS' internal tiling modifications to Neural-Style: https://github.com/VaKonS/neural-style

With this approach, we could use as many separate regions, as you have the patience/time for. This would allow for extremely complex mask images, but without the same memory usage constraints that currently exist.
